### ISSUE TITLE
Camera Upright Visual indicator

### ISSUE THREAD

**Issue by davidearlyoung** [Chen-Yulin/Besiege-Modern-Mod#73]
I suggest a visual marking on the 3d model of the camera block. This would help so that we know sooner what is upright on the physical camera in relation to what is upright to the image it will capture. Mentioning of it in the documentation would be smart too.

**Comment by Chen-Yulin** [comment]
Oh yeah, I will change it as soon as possible

**Comment by Chen-Yulin** [comment]
![image](https://github.com/Chen-Yulin/Besiege-Modern-Mod/assets/81513548/8bebfdfe-3eab-4e64-8578-bc99a9655315)

Newly added white texture along the top edge of the camera
